"""Update relationships and added recipe

Revision ID: 423ddb666dc3
Revises: 7caaf94d944b
Create Date: 2025-10-24 22:13:09.903167

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "423ddb666dc3"
down_revision: Union[str, Sequence[str], None] = "7caaf94d944b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredient_category",
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
        ),
        sa.PrimaryKeyConstraint("ingredient_id", "category_id"),
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=183), nullable=False),
        sa.Column("cooking_time", sa.Integer(), nullable=False),
        sa.Column(
            "difficulty_level",
            sa.Enum("EASY", "MEDIUM", "HARD", name="difficultylevel"),
            nullable=False,
        ),
        sa.Column("portions", sa.Integer(), nullable=False),
        sa.Column("is_vegan", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("instructions", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "recipe_ingredients",
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("recipe_id", "ingredient_id"),
    )
    op.drop_constraint(
        op.f("ingredients_category_id_fkey"), "ingredients", type_="foreignkey"
    )
    op.drop_column("ingredients", "category_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ingredients",
        sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("ingredients_category_id_fkey"),
        "ingredients",
        "categories",
        ["category_id"],
        ["id"],
    )
    op.drop_table("recipe_ingredients")
    op.drop_table("recipes")
    op.drop_table("ingredient_category")
    # ### end Alembic commands ###
