"""Create recipes table

Revision ID: 6d0c7f1c8ce6
Revises: 7caaf94d944b
Create Date: 2025-10-21 19:32:39.697481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0c7f1c8ce6'
down_revision: Union[str, Sequence[str], None] = '7caaf94d944b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=183), nullable=False),
    sa.Column('cooking_time', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.String(), nullable=False),
    sa.Column('portions', sa.Integer(), nullable=False),
    sa.Column('is_vegan', sa.Boolean(), nullable=False),
    sa.Column('instructions', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('ingredients', sa.Column('recipe_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ingredients', 'recipes', ['recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_column('ingredients', 'recipe_id')
    op.drop_table('recipes')
    # ### end Alembic commands ###
