"""Removed uneeded ingredients fields

Revision ID: 91d2cd3df780
Revises: b6638c0bb499
Create Date: 2025-10-05 15:49:46.341223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d2cd3df780'
down_revision: Union[str, Sequence[str], None] = 'b6638c0bb499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('ingredients', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('ingredients', sa.Column('is_vegan', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'ingredients', ['name'])
    op.drop_column('ingredients', 'ing_category')
    op.drop_column('ingredients', 'ing_amount')
    op.drop_column('ingredients', 'ing_grams')
    op.drop_column('ingredients', 'ing_name')
    op.drop_column('ingredients', 'ing_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('ing_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('ingredients', sa.Column('ing_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('ingredients', sa.Column('ing_grams', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('ingredients', sa.Column('ing_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('ingredients', sa.Column('ing_category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ingredients', type_='unique')
    op.drop_column('ingredients', 'is_vegan')
    op.drop_column('ingredients', 'name')
    op.drop_column('ingredients', 'id')
    # ### end Alembic commands ###
