"""add ingredients

Revision ID: b6638c0bb499
Revises: 5fe594072bd8
Create Date: 2025-10-04 22:02:06.865672

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6638c0bb499"
down_revision: Union[str, Sequence[str], None] = "5fe594072bd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredients",
        sa.Column("ing_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ing_name", sa.String(length=100), nullable=False),
        sa.Column("ing_amount", sa.Integer(), nullable=False),
        sa.Column("ing_grams", sa.Integer(), nullable=False),
        sa.Column("ing_category", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("ing_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ingredients")
    # ### end Alembic commands ###
